name: Refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Runs every half hour

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        run: |
          curl --fail --request POST --url https://api.github.com/repos/${{ github.repository }}/pages/builds --header "Authorization: bearer $USER_TOKEN"